name = "stremio-premiumize-addon"
main = "src/index.js"
compatibility_date = "2024-12-02"
workers_dev = true
preview_urls = true
compatibility_flags = [ "nodejs_compat" ]
[observability.logs]
enabled = true
[[kv_namespaces]]
binding = "KV"
id = "f816a40740384fda901a14ab328b65d8"
